development:
  encoding: utf8
  adapter: postgresql
  database: fff_dev
  username: <%= `whoami` %>

test:
  encoding: utf8
  pool: 10
  adapter: postgresql
  database: fff_test
  username: <%= `whoami` %>
