# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 108ce9d3beb1e03efdec3caee438c66e9e0f529197d666ce5ece5b43443ec013273b20390bec5dda815f6a6f54d7d95b00932e8a10f2d5fcd9879a9beed75d7f

test:
  secret_key_base: 57bdff19206c4bd4a02eb496c831a888fcd1921ea5e2e3a48e2be13e29a0fc708dc59f13256514732bb6cc74aaac16e0589e87e489174699587abe1cba68a1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
